### ISSUE TITLE
cmd:setup_jbod provisioner failed

### ISSUE THREAD

**Issue by hessio** [Seagate/cortx-prvsnr#1049]
While trying to verify this guide: [https://github.com/Seagate/cortx/blob/main/doc/scaleout/Installing_CORTX_Software.rst](https://github.com/Seagate/cortx/blob/main/doc/scaleout/Installing_CORTX_Software.rst) I encountered an error with the provisioner command (step4.) of this guide. 

### Command I ran

```
provisioner setup_jbod --source iso --iso-cortx cortx-1.0.0-release-43.iso \
 --iso-cortx-deps cortx-1.0.0-prereqs-43.iso \
 --ha --logfile --logfile-filename /var/log/seagate/provisioner/setup-provisioner.log \
 --config-path config.ini srvnode-1:smc21-m10.colo.seagate.com \
 srvnode-2:smc20-m10.colo.seagate.com srvnode-3:smc19-m10.colo.seagate.com
```

### Error

```
2021-03-26 10:49:17,973 - 140030989285184 - provisioner.__main__ - ERROR - [__main__.py:224]: cmd:setup_jbod provisioner failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/provisioner/__main__.py", line 214, in main
    ret = _main()
  File "/usr/local/lib/python3.6/site-packages/provisioner/__main__.py", line 205, in _main
    return _run_cmd(parsed_args.cmd, *_args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/provisioner/__main__.py", line 94, in _run_cmd
    return _api.run(cmd, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/provisioner/_api.py", line 49, in run
    return SimpleRunner(nowait=nowait).run(command, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/provisioner/runner.py", line 73, in run
    return cmd.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/provisioner/commands/setup_jbod.py", line 60, in run
    nodes, **setup_provisioner_args
  File "/usr/local/lib/python3.6/site-packages/provisioner/commands/setup_provisioner.py", line 1267, in _run
    targets=master_targets
  File "/usr/local/lib/python3.6/site-packages/provisioner/salt.py", line 536, in cmd_run
    'cmd.run', fun_args=[cmd], targets=targets, **kwargs
  File "/usr/local/lib/python3.6/site-packages/provisioner/salt.py", line 667, in run
    return super().run(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/provisioner/salt.py", line 525, in run
    raise SaltCmdResultError(cmd_args, res.fails)
provisioner.errors.SaltCmdResultError: salt command failed, reason {'srvnode-2': 'Traceback (most recent call last):\n  File "<string>", line 1, in <module>\n  File "/usr/local/lib/python3.6/site-packages/provisioner/salt_minion.py", line 57, in ensure_salt_minions_are_ready\n    tries=20, wait=30\n  File "/usr/local/lib/python3.6/site-packages/provisioner/utils.py", line 126, in ensure\n    raise ProvisionerError(\'no more tries\')\nprovisioner.errors.ProvisionerError: no more tries', 'srvnode-3': 'Traceback (most recent call last):\n  File "<string>", line 1, in <module>\n  File "/usr/local/lib/python3.6/site-packages/provisioner/salt_minion.py", line 57, in ensure_salt_minions_are_ready\n    tries=20, wait=30\n  File "/usr/local/lib/python3.6/site-packages/provisioner/utils.py", line 126, in ensure\n    raise ProvisionerError(\'no more tries\')\nprovisioner.errors.ProvisionerError: no more tries'}, args {'targets': '*', 'fun': 'cmd.run', 'fun_args': ['python3 -c "from provisioner import salt_minion; salt_minion.ensure_salt_minions_are_ready([\'srvnode-1\', \'srvnode-2\', \'srvnode-3\'])"'], 'fun_kwargs': {}, 'kw': {'roster_file': '/root/prov/.provisioner/srvnode-1_root@smc21-m10.colo.seagate.com_22__srvnode-2_root@smc20-m10.colo.seagate.com_22__srvnode-3_root@smc19-m10.colo.seagate.com_22/srv/config/roster', 'ssh_options': ['UserKnownHostsFile=/dev/null', 'StrictHostKeyChecking=no']}}
```

**Comment by ypise** [comment]
@hessio 
We need to pick this up for R2.
Could you help with procuring test infra?

**Comment by hessio** [comment]
I have been provisioned this infra. I think you need to submit a request to Trent to procure this. I am happy to help out with this if you need however.
