### ISSUE TITLE
Trying to build CORTX on server using loop devices

### ISSUE THREAD

**Issue by hessio** [Seagate/cortx-prvsnr#1478]
When I run the setup\_provisioner command I get this error:

```
[root@smc73-m02 ~]# provisioner setup_provisioner srvnode-1:$(hostname -f) --logfile --logfile-filename /var/log/seagate/provisioner/setup.log --source rpm --config-path ~/config.ini --dist-type bundle --target-build ${CORTX_RELEASE_REPO}
2021-07-06 05:39:59,786 - INFO - Running provisioner version: 2.0.54
2021-07-06 05:39:59,788 - INFO - Starting to build setup 'srvnode-1_root@smc73-m02.colo.seagate.com_22'
2021-07-06 05:39:59,792 - INFO - Profile location '/root/.provisioner/srvnode-1_root@smc73-m02.colo.seagate.com_22'
2021-07-06 05:39:59,792 - INFO - Preparing setup pillar
2021-07-06 05:39:59,793 - INFO - Generating setup keys [skipped]
2021-07-06 05:39:59,793 - INFO - Generating a roster file
2021-07-06 05:39:59,793 - INFO - Copying config.ini to file root
2021-07-06 05:39:59,800 - INFO - Preparing CORTX repos pillar
2021-07-06 05:39:59,806 - INFO - Ensuring 'srvnode-1' is ready to accept commands
2021-07-06 05:40:01,193 - INFO - Resolving node grains
2021-07-06 05:40:03,254 - INFO - Preparing salt-masters / minions configuration
2021-07-06 05:40:03,265 - INFO - Preparing factory profile
2021-07-06 05:40:03,321 - INFO - Installing Cortx yum repositories
2021-07-06 05:40:12,456 - INFO - Setting up custom python repository
2021-07-06 05:40:17,003 - INFO - Checking passwordless ssh
2021-07-06 05:40:21,651 - INFO - Configuring Firewall
2021-07-06 05:40:26,331 - INFO - Installing SaltStack
2021-07-06 05:40:50,081 - INFO - Installing provisioner from a 'rpm' source
2021-07-06 05:40:57,671 - INFO - Configuring salt minions
2021-07-06 05:41:03,026 - INFO - Configuring salt-masters
2021-07-06 05:41:21,111 - INFO - Copying factory data
2021-07-06 05:41:25,340 - INFO - Installing provisioner API
2021-07-06 05:41:33,287 - INFO - Starting salt minions
2021-07-06 05:41:38,278 - INFO - Ensuring salt-masters are ready
2021-07-06 05:41:42,730 - INFO - Ensuring salt minions are ready
2021-07-06 05:41:46,532 - INFO - Updating release distribution type
2021-07-06 05:41:49,894 - INFO - Updating target build pillar
2021-07-06 05:41:53,157 - INFO - Generating a password for the service user
2021-07-06 05:41:56,482 - INFO - Get release factory version
2021-07-06 05:41:58,222 - INFO - Sync salt modules
2021-07-06 05:42:07,710 - INFO - Configuring provisioner logging
2021-07-06 05:42:17,137 - INFO - Setting unique ClusterID to pillar file on all nodes
2021-07-06 05:42:25,784 - INFO - Refresh machine id on the system
2021-07-06 05:42:35,805 - INFO - Encrypt pillar values and Refresh enclosure id on the system
2021-07-06 05:42:46,059 - ERROR - PROVISIONER FAILED.
Reason: salt command failed, reason {
        srvnode-1: [ERROR   ] Unhandled exception occurred in function "run: 'cluster_id'
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/state.py", line 2154, in call
    *cdata["args"], **cdata["kwargs"]
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2106, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/utils/decorators/__init__.py", line 746, in _decorate
    return self._call_function(kwargs)
  File "/usr/lib/python3.6/site-packages/salt/utils/decorators/__init__.py", line 377, in _call_function
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3.6/site-packages/salt/ext/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/salt/utils/decorators/__init__.py", line 360, in _call_function
    return self._function(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/states/module.py", line 422, in run
    _func, returner=kwargs.get("returner"), func_args=kwargs.get(func)
  File "/usr/lib/python3.6/site-packages/salt/states/module.py", line 467, in _call_function
    mret = salt.utils.functools.call_function(__salt__[name], *func_args, **func_kwargs)
  File "/usr/lib/python3.6/site-packages/salt/utils/functools.py", line 159, in call_function
    return salt_function(*function_args, **function_kwargs)
  File "/var/cache/salt/minion/extmods/modules/pillar_ops.py", line 46, in encrypt
    cluster_id = getattr(sys.modules[__name__], '__grains__')['cluster_id']
  File "/usr/lib/python3.6/site-packages/salt/utils/context.py", line 223, in __getitem__
    return self._dict()[key]
KeyError: 'cluster_id'

local:
  Name: Install cortx-py-utils python dependencies - Function: pip.installed - Result: Clean Started: - 05:42:40.178664 Duration: 1608.092 ms
  Name: cortx-py-utils - Function: pkg.installed - Result: Clean Started: - 05:42:44.032949 Duration: 1235.113 ms
----------
          ID: Encrypt_pillar
    Function: module.run
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3.6/site-packages/salt/state.py", line 2154, in call
                  *cdata["args"], **cdata["kwargs"]
                File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2106, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/utils/decorators/__init__.py", line 746, in _decorate
                  return self._call_function(kwargs)
                File "/usr/lib/python3.6/site-packages/salt/utils/decorators/__init__.py", line 377, in _call_function
                  six.reraise(*sys.exc_info())
                File "/usr/lib/python3.6/site-packages/salt/ext/six.py", line 693, in reraise
                  raise value
                File "/usr/lib/python3.6/site-packages/salt/utils/decorators/__init__.py", line 360, in _call_function
                  return self._function(*args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/states/module.py", line 422, in run
                  _func, returner=kwargs.get("returner"), func_args=kwargs.get(func)
                File "/usr/lib/python3.6/site-packages/salt/states/module.py", line 467, in _call_function
                  mret = salt.utils.functools.call_function(__salt__[name], *func_args, **func_kwargs)
                File "/usr/lib/python3.6/site-packages/salt/utils/functools.py", line 159, in call_function
                  return salt_function(*function_args, **function_kwargs)
                File "/var/cache/salt/minion/extmods/modules/pillar_ops.py", line 46, in encrypt
                  cluster_id = getattr(sys.modules[__name__], '__grains__')['cluster_id']
                File "/usr/lib/python3.6/site-packages/salt/utils/context.py", line 223, in __getitem__
                  return self._dict()[key]
              KeyError: 'cluster_id'
     Started: 05:42:45.269575
    Duration: 7.96 ms
     Changes:

Summary for local
------------
Succeeded: 2
Failed:    1
------------
Total states run:     3
Total run time:   2.851 s,
 }, args {
    "targets": "*",
    "fun": "cmd.run",
    "fun_args": [
        "salt-call state.apply components.system.config.pillar_encrypt"
    ],
    "fun_kwargs": {},
    "kw": {
        "roster_file": "/root/.provisioner/srvnode-1_root@smc73-m02.colo.seagate.com_22/srv/config/roster",
        "ssh_options": [
            "UserKnownHostsFile=/dev/null",
            "StrictHostKeyChecking=no"
        ]
    },
    "secure": false
}
Exiting now..
{'srvnode-1': '[ERROR   ] Unhandled exception occurred in function "run: \'cluster_id\'\n[ERROR   ] An exception occurred in this state: Traceback (most recent call last):\n  File "/usr/lib/python3.6/site-packages/salt/state.py", line 2154, in call\n    *cdata["args"], **cdata["kwargs"]\n  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2106, in wrapper\n    return f(*args, **kwargs)\n  File "/usr/lib/python3.6/site-packages/salt/utils/decorators/__init__.py", line 746, in _decorate\n    return self._call_function(kwargs)\n  File "/usr/lib/python3.6/site-packages/salt/utils/decorators/__init__.py", line 377, in _call_function\n    six.reraise(*sys.exc_info())\n  File "/usr/lib/python3.6/site-packages/salt/ext/six.py", line 693, in reraise\n    raise value\n  File "/usr/lib/python3.6/site-packages/salt/utils/decorators/__init__.py", line 360, in _call_function\n    return self._function(*args, **kwargs)\n  File "/usr/lib/python3.6/site-packages/salt/states/module.py", line 422, in run\n    _func, returner=kwargs.get("returner"), func_args=kwargs.get(func)\n  File "/usr/lib/python3.6/site-packages/salt/states/module.py", line 467, in _call_function\n    mret = salt.utils.functools.call_function(__salt__[name], *func_args, **func_kwargs)\n  File "/usr/lib/python3.6/site-packages/salt/utils/functools.py", line 159, in call_function\n    return salt_function(*function_args, **function_kwargs)\n  File "/var/cache/salt/minion/extmods/modules/pillar_ops.py", line 46, in encrypt\n    cluster_id = getattr(sys.modules[__name__], \'__grains__\')[\'cluster_id\']\n  File "/usr/lib/python3.6/site-packages/salt/utils/context.py", line 223, in __getitem__\n    return self._dict()[key]\nKeyError: \'cluster_id\'\n\nlocal:\n  Name: Install cortx-py-utils python dependencies - Function: pip.installed - Result: Clean Started: - 05:42:40.178664 Duration: 1608.092 ms\n  Name: cortx-py-utils - Function: pkg.installed - Result: Clean Started: - 05:42:44.032949 Duration: 1235.113 ms\n----------\n          ID: Encrypt_pillar\n    Function: module.run\n      Result: False\n     Comment: An exception occurred in this state: Traceback (most recent call last):\n                File "/usr/lib/python3.6/site-packages/salt/state.py", line 2154, in call\n                  *cdata["args"], **cdata["kwargs"]\n                File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2106, in wrapper\n                  return f(*args, **kwargs)\n                File "/usr/lib/python3.6/site-packages/salt/utils/decorators/__init__.py", line 746, in _decorate\n                  return self._call_function(kwargs)\n                File "/usr/lib/python3.6/site-packages/salt/utils/decorators/__init__.py", line 377, in _call_function\n                  six.reraise(*sys.exc_info())\n                File "/usr/lib/python3.6/site-packages/salt/ext/six.py", line 693, in reraise\n                  raise value\n                File "/usr/lib/python3.6/site-packages/salt/utils/decorators/__init__.py", line 360, in _call_function\n                  return self._function(*args, **kwargs)\n                File "/usr/lib/python3.6/site-packages/salt/states/module.py", line 422, in run\n                  _func, returner=kwargs.get("returner"), func_args=kwargs.get(func)\n                File "/usr/lib/python3.6/site-packages/salt/states/module.py", line 467, in _call_function\n                  mret = salt.utils.functools.call_function(__salt__[name], *func_args, **func_kwargs)\n                File "/usr/lib/python3.6/site-packages/salt/utils/functools.py", line 159, in call_function\n                  return salt_function(*function_args, **function_kwargs)\n                File "/var/cache/salt/minion/extmods/modules/pillar_ops.py", line 46, in encrypt\n                  cluster_id = getattr(sys.modules[__name__], \'__grains__\')[\'cluster_id\']\n                File "/usr/lib/python3.6/site-packages/salt/utils/context.py", line 223, in __getitem__\n                  return self._dict()[key]\n              KeyError: \'cluster_id\'\n     Started: 05:42:45.269575\n    Duration: 7.96 ms\n     Changes:   \n\nSummary for local\n------------\nSucceeded: 2\nFailed:    1\n------------\nTotal states run:     3\nTotal run time:   2.851 s'}
 
```

As you can see in stack trace there is an issue with this file `/var/cache/salt/minion/extmods/modules/pillar_ops.py` when I go to this file there is a line that says to test to run these commands:

```
# How to test:
# $ salt-call saltutil.clear_cache
# $ salt-call saltutil.sync_modules && salt-call cortx.conf_update "/opt/seagate/s3/conf/s3config.yaml" s3server
```

The output of these commands is below:  
 

```
[root@smc73-m02 ~]#  salt-call saltutil.clear_cache
local:
    True
```

and

```
[root@smc73-m02 ~]# salt-call saltutil.sync_modules && salt-call cortx.conf_update "/opt/seagate/s3/conf/s3config.yaml" s3server
local:
    - modules.cluster
    - modules.commons
    - modules.component_conf_updater
    - modules.controller_cli
    - modules.gluster
    - modules.lyveutils
    - modules.pillar_ops
    - modules.prvsnr
    - modules.s3server
    - modules.setup_conf
    - modules.sspl
    - modules.sync
'cortx.conf_update' is not available.
```

**Comment by cortx-admin** [comment]
> Board-Genius-Jira commented in Jira Server:

stale commented in Github:

This issue/pull request has been marked as `needs attention` as it has been left pending without new activity for 4 days. Tagging @83bhp @andkononykhin2 for appropriate assignment. Sorry for the delay & Thank you for contributing to CORTX. We will get back to you as soon as possible.

**Comment by cortx-admin** [comment]
> Walter Lopatka commented in Jira Server:

Closed in GitHub

**Comment by cortx-admin** [comment]
> Walter Lopatka commented in Jira Server:

Closed in GitHub

**Comment by cortx-admin** [comment]
> Walter Lopatka commented in Jira Server:

Closed in GitHub
