### ISSUE TITLE
VM : Automated VM Deployment Failing in "Installing 'components.csm'"

### ISSUE THREAD

**Issue by gowthamchinna** [Seagate/cortx-prvsnr#362]
Dev and Release Branch automated VM deployment failing on below state 

Nightly Build : **B364-09-10-2020**  
            - http://eos-jenkins.mero.colo.seagate.com/job/Release_Engineering/job/automated-vm-deployment/291/
Release Build: **2805**
           - http://eos-jenkins.mero.colo.seagate.com/job/Release_Engineering/job/github-work/job/Sanity_Testing_VM/25/console
Provissoner Dev Build: **provisioner_219**
            - http://eos-jenkins.mero.colo.seagate.com/job/Cortx-Dev/job/RHEL-7.7/job/Sanity_Testing_VM/59/

```
----------
          ID: Start CSM agent
    Function: service.running
        Name: csm_agent
      Result: False
     Comment: Running scope as unit run-9988.scope.
              Job for csm_agent.service failed because the control process exited with error code. See "systemctl status csm_agent.service" and "journalctl -xe" for details.
     Started: 13:54:44.045396
    Duration: 4461.159 ms
     Changes:   
----------
```

csm_agent log from test vm

````
[root@ssc-vm-c-0677 csm]# cat csm_agent.log
Sep 11 04:45:26 ssc-vm-c-0677 systemd[1]: Started /usr/bin/systemctl start csm_agent.service.
Sep 11 04:45:30 2020-09-11 04: 45:30 csm_agent ERROR [_init_health_schema] Error occured in reading health schema. Path: /opt/seagate/cortx/provisioner/generated_configs/healthmap/ees-schema.json, [Errno 13] Permission denied: '/opt/seagate/cortx/provisioner/generated_configs/healthmap'
Sep 11 04:45:31 2020-09-11 04: 45:31 csm_agent ERROR [<module>] Traceback (most recent call last):#012  File "/var/jenkins/workspace/Release_Engineering/github-work/CSM-Agent/csm/core/agent/csm_agent.py", line 257, in <module>#012  File "/var/jenkins/workspace/Release_Engineering/github-work/CSM-Agent/csm/core/agent/csm_agent.py", line 77, in init#012  File "/var/jenkins/workspace/Release_Engineering/github-work/CSM-Agent/csm/core/agent/csm_agent.py", line 29, in import_plugin_module#012  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module#012    return _bootstrap._gcd_import(name[level:], package, level)#012  File "<frozen importlib._bootstrap>", line 994, in _gcd_import#012  File "<frozen importlib._bootstrap>", line 971, in _find_and_load#012  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked#012  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked#012  File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module#012    exec(bytecode, module.__dict__)#012  File "csm/plugins/eos/alert.py", line 30, in <module>#012  File "<frozen importlib._bootstrap>", line 971, in _find_and_load#012  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked#012  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked#012  File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module#012    exec(bytecode, module.__dict__)#012  File "/usr/lib/python3.6/site-packages/eos/utils/ha/dm/decision_maker.py", line 108, in <module>#012    class DecisionMaker(object):#012  File "/usr/lib/python3.6/site-packages/eos/utils/ha/dm/decision_maker.py", line 114, in DecisionMaker#012    def __init__(self, decisiondb=DecisionDB()):#012  File "/usr/lib/python3.6/site-packages/eos/utils/ha/dm/repository/decisiondb.py", line 47, in __init__#012    self.storage = DataBaseProvider(conf)#012  File "/usr/lib/python3.6/site-packages/eos/utils/data/db/db_provider.py", line 200, in __init__#012    raise MalformedConfigurationError(f"Couldn't import '{model.import_path}'")#012eos.utils.errors.MalformedConfigurationError: error(4101): Internal error: Couldn't import 'eos.utils.product_features.model.UnsupportedFeaturesModel'
Sep 11 04:45:31 ssc-vm-c-0677 systemd[1]: csm_agent.service: control process exited, code=exited status=1
Sep 11 04:45:31 ssc-vm-c-0677 systemd[1]: Unit csm_agent.service entered failed state.
Sep 11 04:45:31 ssc-vm-c-0677 systemd[1]: csm_agent.service failed.

````

tagging @ypise @sradhanand-pati @priyankdal

**Comment by ypise** [comment]
The issue has been addressed based on the https://jts.seagate.com/browse/EOS-13084.
